include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
  exclude:
    - build/**

linter:
  rules:
    - always_declare_return_types
    - avoid_dynamic_calls
    - avoid_null_checks_in_equality_operators
    - avoid_print
    - avoid_slow_async_io
    - cancel_subscriptions
    - deprecated_member_use_from_same_package
    - directives_ordering
    - implicit_reopen
    - invalid_case_patterns
    - no_adjacent_strings_in_list
    - no_literal_bool_comparisons
    - no_self_assignments
    - omit_local_variable_types
    - package_prefixed_library_names
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_if_elements_to_conditional_expressions
    - prefer_single_quotes
    - public_member_api_docs
    - sort_child_properties_last
    - test_types_in_equals
    - throw_in_finally
    - unawaited_futures
    - unnecessary_statements
